### ISSUE TITLE
QueryPerformanceCounter issues

### ISSUE THREAD

**Issue by YaLTeR** [Hourglass-Resurrection/Hourglass-Resurrection#30]
Some external DLLs (notably, NVidia's graphics driver DLLs) (who knows, maybe some games do this as well) are calling QueryPerformanceCounter() / <...>Frequency() similarly to this:

```
QueryPerformanceFrequency(&Freq);
QueryPerformanceCounter(&PerfCount);
do
    QueryPerformanceCounter(&Temp);
while (Temp == PerfCount);
```

in the main thread (usually before any graphics were initialized, so before any frames are being drawn, which means before any time starts to pass), which results in an indefinite loop.

In the case with NVidia's graphics DLLs, it's basically impossible to launch any games under Hourglass because that piece of code is reached inside `Direct3DCreate9()`.

A possible fix would be to call the original QPC() / QPF() in any case where caller is untrusted, however I'm afraid that this can cause indeterministic behavior (if the said external DLL measures time for something important in the game).

If you're experiencing the mentioned issues with `Direct3DCreate9()` a quick and dirty fix is to call the original QPC() / QPF() when inside `Direct3DCreate9()`.

**Comment by Warepire** [comment]
Since #69 this bug can now be resolved.
