### ISSUE TITLE
Make Hourglass multiplatform

### ISSUE THREAD

**Issue by Danfun64** [Hourglass-Resurrection/Hourglass-Resurrection#41]
Currently, Hourglass is only available for Windows, and thus can only record Windows games. It would be nice if it can be redesigned so that it can record games on Mac, Linux, and other devices.

I understand completely if you reject this due to being too big or too complex, but it would be REALLY nice to have.

**Comment by YaLTeR** [comment]
How Hourglass works is hooking a whole lot of Windows API functions. To make a Hourglass-type application for another platform you have to hook a whole lot of other platform's API functions that work very differently from Windows API.

A major part of Hourglass is so platform-specific that it cannot be just redesigned to support other platforms, it needs to be written separately for each of them.

**Comment by Danfun64** [comment]
I thought as much...

My suggestion would be to make Hourglass modular: Make a common base that all OS can use, and then put OS specific code as modules.

Of course, I'm not a programmer, nor am I directly involved in this project, so again, I would understand if you reject this idea.

**Comment by Warepire** [comment]
There's not much that would be possible to share across operating systems, it would probably make more sense to just create different projects all-together.

**Comment by Danfun64** [comment]
Ahh... pity.
