### ISSUE TITLE
Caller is untrusted should be re-implemented

### ISSUE THREAD

**Issue by Warepire** [Hourglass-Resurrection/Hourglass-Resurrection#52]
The caller-is-untrusted functionality which detects if a call is made by the game or by a OS DLL should be re-implemented to determinate the trust using a stack trace instead of using a gate system stored in the TLS.

This will eliminate a lot of hazardous code, and make the detection itself safer.

**Comment by Warepire** [comment]
Currently the interface we use for `dbghelp.dll` called `extendedtrace` is not flexible enough to do anything near what we need for this. The interface should probably be dropped and a new one implemented instead, in a C++ style.

**Comment by YaLTeR** [comment]
The PR for replacing `extendedtrace` just landed, making this able to progress further. Next step is re-implementing using IPC.
